apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  generation: 1
  labels:
    app: {{PROJECT_NAME}}
  name: {{PROJECT_NAME}}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{PROJECT_NAME}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{PROJECT_NAME}}
    spec:
      containers:
        - env:
            - name: CONTAINER_ENV
              value: {{ENVIRONMENT}}
            - name: CONTAINER_IP_ADDR
              value: 172.12.1.1
            - name: CONTAINER_REGION
              value: ALI_BJ
            - name: CONTAINER_NAME
              value: ALI_BJ_TEST
            - name: CONTAINER_PROGRAM
              value: APP
            - name: CONTAINER_PROJ
              value: {{PROJECT_NAME}}
          image: >-
            xq-harbor-ingress.ce027df6a3ed8476bb82b2cd0e6f6f219.cn-beijing.alicontainer.com/lib/{{PROJECT_NAME}}:{{GIT_VERSION}}
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - /data/deploy/deploy_3_start.sh
            preStop:
              exec:
                command:
                  - /data/deploy/deploy_1_stop.sh
          name: xueqiu-push-user
          ports:
            - containerPort: 10000
              name: grpc
              protocol: TCP
            - containerPort: 8080
              name: web
              protocol: TCP
          resources:
            requests:
              cpu: '4'
              memory: 5Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: harbor-ack
      restartPolicy: Always
      securityContext:
        runAsUser: 1103
      terminationGracePeriodSeconds: 30